[package]
name = "zolt-macros"
description = "Macros for the 'zolt' crate"
version.workspace = true
authors.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
colored.workspace = true
zolt-proc.workspace = true
